package datos;

//AQUÍ SE COGERÁN LOS DATOS QUE INTRODUCE EL USUARIO POR TECLADO EN EL MAIN SOBRE EL BARCO
//PARA POSTERIORMENTE PASAR ESTOS DATOS A LA CLASE BARCO QUE HAY EN MODEL

public class DatosBarco {
	
	

}
